spring:
  application:
    name: provider-service

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1

demo:
  service:
    version: 1.0.0
    name: demoService
